config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get '/signup/:invitation_token', :controller => 'users', :action => 'new'

  resources :sessions
  resources :memberships
  resources :groups
  resources :users
  resources :invites
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :memberships
    has_many :users, through: :memberships
    belongs_to :owner, class_name: 'User', foreign_key: :owner_id
    has_many :invites



   def non_group_memberships 
    Membership.all.select {|mem| mem.group_id != self.id}
   end

   def non_group_users
    non_group_memberships.collect {|mem| mem.user.name}
   end 

    

 
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_action :authenticate!, except: [:index, :show]
    def index 
        @groups = Group.all
    end 

    def show 
        @group = Group.find(params[:id])
        # @membership = @group.users
        # @user = User.find(params[:id]) if current_user
    end 

    def new 
        @group = Group.new
    end 

    def create 
        @group = Group.new(group_params)
        @group.owner_id = current_user.id if current_user
        if @group.save
            Membership.create(group_id: "#{@group.id}", user_id: "#{@current_user.id}")
            redirect_to group_path(@group)
        else 
            render :new 
        end 
    end 

    def edit 
        @group = Group.find(params[:id])
    end

    def update 
        @group = Group.find(params[:id])
        if @group.update(group_params)
            redirect_to groups_path
        else  
            render :edit 
        end 
    end 

    private

    def group_params
        params.require(:group).permit(:name)
    end 
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
    <%=f.label :name %>
    <%=f.text_field :name %>

   
    <%= f.submit %>
<% end %>

app/views/groups/edit.html.erb
 <%= render("form")%>
 <h4>Invite</h4>
 <%= form_for @invite, :url => invites_path do |f| %>
    <%= f.hidden_field :group_id, value => @invite.group_id %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.submit 'Send' %>
<% end %>

app/views/groups/index.html.erb
<h2>All Groups</h2>
   
    <ul >
    <% @groups.each do |group| %> 
        <li >
          <h4><%= link_to(group.name, group_path(group)) %></h4>
        </li>
    <% end %>
    
    </ul>
  </
  <% unless  %>
    
  <% end %>
  >
<br>
 
  <h5 >
    <%= link_to('New Group', new_group_path) %>
  </h5>

app/views/groups/new.html.erb
<%= render("form")%>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>
<h3><%=@group.owner.name%></h3>
<h4>Members:</h4>
<ul>
  <% @group.users.each do |user| %>
    <li><%= user.name %></li>
  <% end %>
</ul>
<% if can? :update, @group %>
  <%= link_to "Add new Member", new_membership_path %>
<%end%>
<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>