config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get '/signup/:invitation_token', :controller => 'users', :action => 'new'

  resources :sessions
  resources :memberships
  resources :groups
  resources :users
  resources :invites
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :memberships
    has_many :groups, through: :memberships
    has_many :owned_groups, foreign_key: 'owner_id', class_name: 'Group'
    belongs_to :invite
    has_many :sent_invites, :class_name => "Invite", :foreign_key => 'sender_id'

    has_secure_password

  
    validates_uniqueness_of :email

    before_create :set_invitation_limit

    def invitation_token
        invite.token if invite
    end
      
    def invitation_token=(token)
        self.invite = Invite.find_by_token(token)
    end
    
    private

    def set_invitation_limit
        self.invitation_limit = 50
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index 
        @users = User.all
    end 

    def show 
        @user = User.find(params[:id])
    end 

    def new 
        @user = User.new(:invitation_token => params[:invitation_token])
        @user.email = @user.invite.recipient_email if @user.invite 
    end 

    def create 
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          redirect_to groups_path, notice: "Thank you for signing up!"
        else
          render "new"
        end
    end 

    def edit 
        @user = User.find(params[:id])
    end

    def update 
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to users_path
        else  
            render :edit 
        end 
    end 

    private

    def user_params
        params.require(:user).permit(:name, :password, :email, :invite_id, :invitation_limit, :invitation_token)
    end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_bar.html.erb
<div id="user_bar">
<% if logged_in? %>
  <p>Welcome <%= current_user.login %> (<%= link_to 'log-out', logout_path %>)</p>
  <% if current_user.invitation_limit > 0 %>
    <p>
      <%= link_to 'Send invitation', new_invite_path %>
      (<%= current_user.invitation_limit %> left)
    </p>
  <% end %>
<% else %>
  <p>If you have an account, <%= link_to "Log-in", login_path %></p>
<% end %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.hidden_field :invitation_token %>
  </div>


  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>